displayName=agility rooftop notifications
author=cs
description=Utilizes the RuneLite notification system to alert you inbetween rooftop obstacles with extended options.
tags=agility,rooftop,rooftopcourses,skilling,xp,xpdrop,roof,notification,notifications,obstacles,forcenotification
version=v1.0
plugins=com.agilityrooftopnotifications.AgilityRooftopNotificationsPlugin
build=standard